# Generated by Django 4.0.4 on 2022-06-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(default='192.168.1.1', max_length=12)),
                ('pc_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='', max_length=2000)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdoor.computer')),
            ],
        ),
    ]
