# Generated by Django 4.0.4 on 2022-06-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0002_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='output',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
