# Generated by Django 4.0.4 on 2022-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0003_alter_output_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
