# Generated by Django 4.0.4 on 2022-06-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0005_alter_output_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
