# Generated by Django 4.0.4 on 2022-06-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0006_alter_output_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
