# Generated by Django 4.0.4 on 2022-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0007_alter_command_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_data', models.TextField(default='')),
            ],
        ),
    ]
