# Generated by Django 4.0.4 on 2022-06-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
