# Generated by Django 4.0.4 on 2022-06-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0010_computer_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='last_online',
            field=models.DateTimeField(),
        ),
    ]
