# Generated by Django 4.0.4 on 2022-06-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0011_alter_computer_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip_addr',
            field=models.CharField(default='192.168.1.1', max_length=50),
        ),
    ]
