# Generated by Django 4.0.6 on 2023-02-25 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backdoor', '0014_alter_computer_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='ping',
            field=models.CharField(default='0ms', max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
